# Generated by Django 5.2.17 on 2026-08-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Denominación del material. Ej: "Acrílico rojo carmín".', max_length=80, verbose_name='nombre')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DISCONTINUADO', 'Discontinuado')], default='ACTIVO', help_text='Indica si el material continúa en uso.', max_length=15, verbose_name='estado')),
                ('disponibilidad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='ALTA', help_text='Nivel estimado de existencias. Cualitativo, no numérico.', max_length=5, verbose_name='disponibilidad')),
                ('descripcion', models.CharField(blank=True, help_text='Distingue el material de sus variantes: tono, marca, presentación.', max_length=500, verbose_name='descripción')),
                ('url_imagen', models.ImageField(blank=True, help_text='Opcional. Facilita el reconocimiento visual del material.', max_length=255, null=True, upload_to='materiales/', verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
                'ordering': ['nombre'],
            },
        ),
    ]
