# Generated by Django 5.2.17 on 2026-08-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Denominación de la categoría. Ej: "Aros", "Harry Potter".', max_length=30, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, help_text='Aclaración sobre qué agrupa, si el nombre no alcanza.', max_length=100, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
    ]
