# Generated by Django 5.2.17 on 2026-08-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activa'), ('BAJA', 'De baja')], default='ACTIVO', help_text='Una categoría de baja retira sus productos del catálogo.', max_length=6, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('TIPO', 'Tipo de accesorio'), ('TEMATICA', 'Temática')], default='TIPO', help_text='Si agrupa por clase de accesorio o por temática.', max_length=8, verbose_name='tipo'),
        ),
    ]
