# Generated by Django 5.2.17 on 2026-09-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(error_messages={'unique': 'Ya tenés un cliente con ese usuario.'}, help_text='Sin el @ y en minúscula. Identifica al cliente.', max_length=30, unique=True, verbose_name='usuario de Instagram')),
                ('nombre', models.CharField(help_text='Nombre de pila del cliente. Ej: "Sofía".', max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(blank=True, help_text='Opcional. Muchos clientes solo dejan el nombre.', max_length=50, verbose_name='apellido')),
                ('email', models.EmailField(blank=True, help_text='Opcional. Sirve para mandarle el comprobante.', max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['instagram'],
            },
        ),
    ]
