# Generated by Django 5.2.17 on 2026-09-01 23:31

import config.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='url_imagen',
            field=models.ImageField(blank=True, help_text='Opcional. Facilita el reconocimiento visual del material.', max_length=255, null=True, upload_to='materiales/', validators=[config.validadores.validar_tamano_archivo], verbose_name='imagen'),
        ),
    ]
