# Generated by Django 5.2.17 on 2026-08-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe una categoría con este nombre.'}, help_text='Denominación de la categoría. Ej: "Aros", "Harry Potter".', max_length=30, unique=True, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('TIPO', 'Tipo de accesorio'), ('TEMATICA', 'Temática')], default='TIPO', help_text='Si agrupa por clase de accesorio o por temática.', max_length=8, verbose_name='tipo')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activa'), ('BAJA', 'De baja')], default='ACTIVO', help_text='Una categoría de baja retira sus productos del catálogo.', max_length=6, verbose_name='estado')),
                ('descripcion', models.CharField(blank=True, help_text='Aclaración sobre qué agrupa, si el nombre no alcanza.', max_length=100, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['tipo', 'nombre'],
            },
        ),
    ]
