# Generated by Django 5.2.17 on 2026-09-17 21:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0002_alter_material_url_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MATERIALES', 'Materiales'), ('PUBLICIDAD', 'Publicidad'), ('OTRO', 'Otro')], help_text='Si es una compra de materiales, publicidad u otro gasto.', max_length=10, verbose_name='tipo')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Lo que salió. Si el gasto es de materiales lo calcula el sistema sumando los subtotales; si no, se carga a mano y tiene que ser mayor a cero.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, help_text='Cuándo se hizo el gasto. Nace con la fecha de hoy y se puede corregir.', verbose_name='fecha')),
                ('descripcion', models.CharField(blank=True, help_text='Opcional. Qué se compró o para qué fue. Ej: "Reposición mensual en Casa Luján".', max_length=200, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos',
                'ordering': ['-fecha', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='gasto_monto_no_negativo'), models.CheckConstraint(condition=models.Q(('tipo', 'MATERIALES'), ('monto__gt', 0), _connector='OR'), name='gasto_monto_positivo_salvo_materiales')],
            },
        ),
        migrations.CreateModel(
            name='MaterialDelGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cuántas unidades se compraron.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Cuánto se pagó por cada unidad en esta compra. Tiene que ser mayor a cero.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='precio unitario')),
                ('gasto', models.ForeignKey(help_text='La compra en la que se pagó este material.', on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='gastos.gasto', verbose_name='gasto')),
                ('material', models.ForeignKey(help_text='El material comprado. No se puede eliminar mientras figure en un gasto.', on_delete=django.db.models.deletion.PROTECT, related_name='en_gastos', to='materiales.material', verbose_name='material')),
            ],
            options={
                'verbose_name': 'material del gasto',
                'verbose_name_plural': 'materiales del gasto',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('gasto', 'material'), name='material_del_gasto_unico'), models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='material_del_gasto_cantidad_minima'), models.CheckConstraint(condition=models.Q(('precio_unitario__gt', 0)), name='material_del_gasto_precio_unitario_positivo')],
            },
        ),
    ]
