# Generated by Django 5.2.17 on 2026-10-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Opcional. Qué se compró o para qué fue.', max_length=200, verbose_name='descripción'),
        ),
    ]
