# Generated by Django 5.2.17 on 2026-09-08 22:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0006_alter_imagenproducto_orden_alter_imagenproducto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PRODUCCION', 'En producción'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', help_text='El avance del pedido tal como lo ve el cliente.', max_length=20, verbose_name='estado')),
                ('fecha_pedido', models.DateField(default=django.utils.timezone.localdate, help_text='Cuándo se confirmó el encargo. Nace con la fecha de hoy y se puede corregir.', verbose_name='fecha del pedido')),
                ('fecha_entrega_estimada', models.DateField(blank=True, help_text='Opcional. Es la que se le comunica al cliente y puede cambiar.', null=True, verbose_name='fecha de entrega estimada')),
                ('fecha_entrega_real', models.DateField(blank=True, help_text='Opcional. Se completa al pasar el pedido a Entregado.', null=True, verbose_name='fecha de entrega real')),
                ('envio_a_cargo', models.CharField(choices=[('MIO', 'A cargo mío'), ('CLIENTE', 'A cargo del cliente')], default='CLIENTE', help_text='Quién paga el envío. Solo el que está a cargo mío suma al total del pedido.', max_length=7, verbose_name='envío a cargo')),
                ('direccion_entrega', models.CharField(blank=True, help_text='Opcional. Calle y número, localidad, referencias.', max_length=100, verbose_name='dirección de entrega')),
                ('costo_entrega', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Se cobra cuando el envío está a cargo mío.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='costo de entrega')),
                ('cliente', models.ForeignKey(help_text='Quién hizo el encargo. No se puede eliminar mientras tenga pedidos.', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-fecha_pedido', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductoDelPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Se copia del producto al registrarlo. Si después cambia el del catálogo, este no.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio')),
                ('cantidad', models.PositiveIntegerField(help_text='Cuántas unidades iguales de esta pieza lleva el pedido.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('MODELADO', 'Modelado'), ('SECADO', 'Secado'), ('PINTURA_BARNIZ', 'Pintura-Barniz'), ('TERMINADO', 'Terminado')], default='PENDIENTE', help_text='La etapa productiva de estas piezas. No depende del estado del pedido.', max_length=14, verbose_name='estado')),
                ('fecha_cambio_estado', models.DateField(default=django.utils.timezone.localdate, help_text='Desde cuándo la pieza está en esta etapa.', verbose_name='fecha del último cambio de estado')),
                ('descripcion', models.CharField(blank=True, help_text='Opcional. Color, medida, lo que acordaron. Ej: "Verde agua, con dorado".', max_length=300, verbose_name='descripción')),
                ('pedido', models.ForeignKey(help_text='El pedido que incluye esta pieza.', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='pedidos.pedido', verbose_name='pedido')),
                ('producto', models.ForeignKey(help_text='La pieza encargada. No se puede eliminar mientras esté en un pedido.', on_delete=django.db.models.deletion.PROTECT, related_name='en_pedidos', to='productos.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'producto del pedido',
                'verbose_name_plural': 'productos del pedido',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('costo_entrega__gte', 0)), name='pedido_costo_entrega_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='productodelpedido',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='producto_del_pedido_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='productodelpedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='producto_del_pedido_cantidad_minima'),
        ),
    ]
