# Generated by Django 5.2.17 on 2026-09-12 15:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SENA', 'Seña'), ('PAGO_RESTANTE', 'Pago restante'), ('PAGO_COMPLETO', 'Pago completo')], default='SENA', help_text='Si es la seña, el pago restante o el pago completo.', max_length=13, verbose_name='tipo')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Cuánto pagó. Tiene que ser mayor a cero.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, help_text='Cuándo lo pagó. Nace con la fecha de hoy y se puede corregir.', verbose_name='fecha')),
                ('medio', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], default='TRANSFERENCIA', help_text='Cómo lo pagó.', max_length=13, verbose_name='medio')),
                ('pedido', models.ForeignKey(help_text='El pedido que se está pagando.', on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='pedidos.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'cobro',
                'verbose_name_plural': 'cobros',
                'ordering': ['-fecha', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='cobro_monto_positivo')],
            },
        ),
    ]
