# Generated by Django 5.2.17 on 2026-09-01 19:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(blank=True, help_text='Cuánto lleva, en las palabras de la emprendedora. Ej: "dos gotas".', max_length=50, verbose_name='cantidad')),
                ('material', models.ForeignKey(help_text='El material que se usa. No se puede eliminar mientras esté acá.', on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='materiales.material', verbose_name='material')),
            ],
            options={
                'verbose_name': 'material del producto',
                'verbose_name_plural': 'materiales del producto',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Denominación de la pieza. Ej: "Aros Hedwig".', max_length=80, verbose_name='nombre')),
                ('precio_actual', models.DecimalField(decimal_places=2, help_text='Precio vigente. El de los pedidos ya registrados no cambia.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio actual')),
                ('dificultad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], help_text='Cuánto trabajo demanda producir la pieza.', max_length=5, verbose_name='dificultad')),
                ('paso_a_paso', models.TextField(blank=True, help_text='Instrucciones de elaboración. Uso interno, no va al catálogo.', verbose_name='paso a paso')),
                ('es_personalizado', models.BooleanField(default=False, help_text='Un encargo puntual de un cliente. No se muestra en el catálogo.', verbose_name='es personalizado')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'De baja')], default='ACTIVO', help_text='Un producto de baja se retira del catálogo y queda de solo lectura.', max_length=6, verbose_name='estado')),
                ('categorias', models.ManyToManyField(blank=True, help_text='Un producto sin categorías depende solo de su propio estado.', related_name='productos', to='categorias.categoria', verbose_name='categorías')),
                ('materiales', models.ManyToManyField(blank=True, help_text='Los materiales que lleva la pieza, con su cantidad.', related_name='productos', through='productos.MaterialProducto', to='materiales.material', verbose_name='materiales')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='materialproducto',
            name='producto',
            field=models.ForeignKey(help_text='La pieza a la que pertenece esta línea de la receta.', on_delete=django.db.models.deletion.CASCADE, related_name='materiales_usados', to='productos.producto', verbose_name='producto'),
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Archivo de la foto. Pillow valida que sea una imagen real.', max_length=255, upload_to='productos/', verbose_name='imagen')),
                ('titulo', models.CharField(blank=True, help_text='Opcional. Aclara qué muestra la foto. Ej: "Detalle del broche".', max_length=50, verbose_name='título')),
                ('tipo', models.CharField(choices=[('REFERENCIA', 'Referencia'), ('RESULTADO', 'Resultado')], default='RESULTADO', help_text='Referencia la manda el cliente; resultado es la pieza terminada.', max_length=10, verbose_name='tipo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Posición en la galería. La de orden más bajo es la principal.', verbose_name='orden')),
                ('producto', models.ForeignKey(help_text='La pieza que muestra esta imagen.', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'imagen del producto',
                'verbose_name_plural': 'imágenes del producto',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_actual__gte', 0)), name='producto_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='materialproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'material'), name='material_producto_unico'),
        ),
    ]
