# Generated by Django 5.2.17 on 2026-09-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, help_text='PEs el texto que lee el cliente en el catálogo.', max_length=500, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='materialproducto',
            name='cantidad',
            field=models.CharField(blank=True, help_text='Cuánto lleva, en palabras. Ej: "dos gotas".', max_length=50, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='paso_a_paso',
            field=models.TextField(blank=True, help_text='Descripcion del paso a paso para poder recrear la pieza en el futuro.', verbose_name='paso a paso'),
        ),
    ]
