# Generated by Django 5.2.17 on 2026-09-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_descripcion_alter_materialproducto_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Es el texto que lee el cliente en el catálogo.', max_length=500, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='es_personalizado',
            field=models.BooleanField(default=False, help_text='Encargo puntual de un cliente. No se muestra en el catálogo.', verbose_name='es personalizado'),
        ),
    ]
