# Generated by Django 5.2.17 on 2026-09-01 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialproducto',
            name='producto',
            field=models.ForeignKey(help_text='La pieza que lleva este material.', on_delete=django.db.models.deletion.CASCADE, related_name='materiales_usados', to='productos.producto', verbose_name='producto'),
        ),
    ]
