# Generated by Django 5.2.17 on 2026-09-01 23:31

import config.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_materialproducto_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(help_text='Archivo de la foto. Pillow valida que sea una imagen real.', max_length=255, upload_to='productos/', validators=[config.validadores.validar_tamano_archivo], verbose_name='imagen'),
        ),
    ]
