# Generated by Django 5.2.17 on 2026-09-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_imagenproducto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Posición dentro de su tipo. La de orden más bajo entre las de resultado es la principal.', verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='tipo',
            field=models.CharField(choices=[('REFERENCIA', 'Referencia'), ('RESULTADO', 'Resultado')], default='RESULTADO', help_text='Referencia es una guía para hacer la pieza; resultado es la pieza terminada.', max_length=10, verbose_name='tipo'),
        ),
    ]
